apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: bootcamp-dev-restaurant
  labels:
    app: restaurant-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: restaurant-deployment
