apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
  namespace: bootcamp-dev-restaurant
  labels:
    app: restaurant-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-deployment
  template:
    metadata:
      labels:
        app: restaurant-deployment
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - localhost
        - ip: 192.168.65.2
          hostnames:
            - host.minikube.internal
      containers:
        - name: restaurant-deployment
          image: restaurantt:1.0
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /restaurant/actuator/health
              port: http
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /restaurant/actuator/health
              port: http
            failureThreshold: 3
            periodSeconds: 30
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx1024m"
            - name: JAVA_CONFIGS
              value: "/home/app/config/application.properties"
            - name: TIME_ZONE
              value: "-Dlogback.timezone=Asia/Bangkok"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: restaurant-volume
              mountPath: /home/app/config/application.properties
              subPath: application.properties
      volumes:
        - name: restaurant-volume
          configMap:
            name: restaurant-configmap

