apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-configmap
  namespace: bootcamp-dev-restaurant
data:
  application.properties: |+
   app.text=hello from kube
   server.servlet.context-path=/restaurant
   kafka.bootstrap-servers=192.168.65.2:39092
   spring.kafka.consumer.auto-offset-reset=latest
   kafka.topics.regist.get.order=topic.get.order
   kafka.topics.regist.update.order=topic.update.order
   kafka.consumer.group-id.get=group.regis.topic.get
   kafka.consumer.group-id.update=group.regis.topic.update
   spring.datasource.username=root
   spring.datasource.password=password
   spring.datasource.url=jdbc:mysql://192.168.65.2:3306/restaurant
   spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
